package com.aritradas.medai.utils

import android.app.Activity
import android.content.Context
import android.content.ContextWrapper
import android.util.Patterns
import com.aritradas.medai.domain.model.PrescriptionSummary
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object UtilsKt {

    fun Context.findActivity(): Activity? = when (this) {
        is Activity -> this
        is ContextWrapper -> baseContext.findActivity()
        else -> null
    }

    fun validateName(name: String?): Boolean {
        if (name.isNullOrEmpty() || name.trim().isEmpty()) {
            return false
        }

        val trimmedName = name.trim()

        // Check minimum length
        if (trimmedName.length < 2) {
            return false
        }

        // Check if name contains only letters, spaces, and dots
        val namePattern = "^[A-Za-z.\\s]+$"
        if (!trimmedName.matches(Regex(namePattern))) {
            return false
        }

        // Check that each word is valid (no consecutive spaces or dots)
        return trimmedName.split("\\s+".toRegex())
            .all { word ->
                word.isNotEmpty() &&
                        word.matches(Regex("^[A-Za-z]+\\.?[A-Za-z]*$"))
            }
    }


    fun validateEmail(email: String?): Boolean {
        return email != null && Patterns.EMAIL_ADDRESS.matcher(email).matches()
    }

    fun validatePassword(pw: String): Boolean {
        return pw.length >= 8 && pw.any { it.isLetter() } && pw.any { it.isDigit() }
    }

    fun getInitials(name: String): String {
        val words = name.trim().split(" ")
        return when {
            words.size == 1 -> words[0].take(2)
            words.size >= 2 -> words[0].take(1) + words[1].take(1)
            else -> ""
        }
    }

    fun formatSummaryForSharing(summary: PrescriptionSummary): String {
        val stringBuilder = StringBuilder()

        stringBuilder.append("📋 PRESCRIPTION SUMMARY\n")
        stringBuilder.append("Generated by MedAI\n\n")

        if (summary.summary.isNotEmpty()) {
            stringBuilder.append("📝 OVERVIEW:\n")
            stringBuilder.append("${summary.summary}\n\n")
        }

        if (summary.prescriptionReason.isNotEmpty()) {
            stringBuilder.append("🎯 PRESCRIBED FOR:\n")
            stringBuilder.append("${summary.prescriptionReason}\n\n")
        }

        if (summary.medications.isNotEmpty()) {
            stringBuilder.append("💊 MEDICATIONS:\n")
            summary.medications.forEach { medication ->
                stringBuilder.append("• ${medication.name}\n")
                if (medication.dosage.isNotEmpty()) {
                    stringBuilder.append("  Dosage: ${medication.dosage}\n")
                }
                if (medication.frequency.isNotEmpty()) {
                    stringBuilder.append("  Frequency: ${medication.frequency}\n")
                }
                if (medication.duration.isNotEmpty()) {
                    stringBuilder.append("  Duration: ${medication.duration}\n")
                }
                stringBuilder.append("\n")
            }
        }

        if (summary.stepsToCure.isNotEmpty()) {
            stringBuilder.append("🔄 STEPS TO GET CURED:\n")
            summary.stepsToCure.forEach { step ->
                stringBuilder.append("• $step\n")
            }
            stringBuilder.append("\n")
        }

        if (summary.warnings.isNotEmpty()) {
            stringBuilder.append("⚠️ IMPORTANT POINTS:\n")
            summary.warnings.forEach { warning ->
                stringBuilder.append("• $warning\n")
            }
            stringBuilder.append("\n")
        }

        stringBuilder.append("⚠️ DISCLAIMER:\n")
        stringBuilder.append("This is AI-generated content for informational purposes only. ")
        stringBuilder.append("Please consult with your healthcare provider before making any medical decisions.\n\n")

        stringBuilder.append(
            "Generated on: ${
                SimpleDateFormat(
                    "MMM dd, yyyy 'at' hh:mm a",
                    Locale.getDefault()
                ).format(Date())
            }"
        )

        return stringBuilder.toString()
    }

    fun formatReportSummaryForSharing(summary: com.aritradas.medai.domain.model.MedicalReportSummary): String {
        val stringBuilder = StringBuilder()

        stringBuilder.append("📋 MEDICAL REPORT SUMMARY\n")
        stringBuilder.append("Generated by MedAI\n\n")

        if (summary.summary.isNotEmpty()) {
            stringBuilder.append("📝 REPORT OVERVIEW:\n")
            stringBuilder.append("${summary.summary}\n\n")
        }

        if (summary.warnings.isNotEmpty()) {
            stringBuilder.append("⚠️ IMPORTANT POINTS:\n")
            summary.warnings.forEach { warning ->
                stringBuilder.append("• $warning\n")
            }
            stringBuilder.append("\n")
        }

        stringBuilder.append("⚠️ MEDICAL DISCLAIMER:\n")
        stringBuilder.append("This is AI-generated content for informational purposes only. ")
        stringBuilder.append("Please consult with your healthcare provider for proper medical interpretation ")
        stringBuilder.append("and do not use this as a substitute for professional medical advice.\n\n")

        stringBuilder.append("Generated on: ${SimpleDateFormat("MMM dd, yyyy 'at' hh:mm a", Locale.getDefault()).format(Date())}")

        return stringBuilder.toString()
    }
}
